language: node_js
env:
 - CODECOV_TOKEN="f4e536ee-7ad3-4192-ab82-d8336e15dc0b"
node_js:
  - 'node'
before_script:
  - npm install
  - npm run lint
script:
   - npm run test
   - npm run report-coverage
